CREATE TABLE admin
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    email               VARCHAR(255),
    password            VARCHAR(255),
    is_active           BOOLEAN,
    uuid                UUID,
    account_expired     BOOLEAN,
    credentials_expired BOOLEAN,
    account_locked      BOOLEAN,
    role                VARCHAR(255)
);

CREATE TABLE address
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cep         VARCHAR(255),
    logradouro  VARCHAR(255),
    complemento VARCHAR(255),
    numero      INTEGER,
    bairro      VARCHAR(255),
    localidade  VARCHAR(255),
    uf          VARCHAR(255),
    ibge        VARCHAR(255),
    gia         VARCHAR(255),
    ddd         VARCHAR(255),
    siafi       VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE doctor
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    crm                 VARCHAR(255),
    email               VARCHAR(255),
    password            VARCHAR(255),
    is_active           BOOLEAN,
    specialty           VARCHAR(255),
    uuid                UUID,
    account_expired     BOOLEAN,
    credentials_expired BOOLEAN,
    account_locked      BOOLEAN,
    role                VARCHAR(255),
    address_id          BIGINT,
    CONSTRAINT pk_doctor PRIMARY KEY (id)
);

ALTER TABLE doctor
    ADD CONSTRAINT FK_DOCTOR_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

CREATE TABLE patient
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID,
    nome                VARCHAR(255),
    email               VARCHAR(255),
    senha               VARCHAR(255),
    telefone            VARCHAR(255),
    cpf                 VARCHAR(255),
    create_at           TIMESTAMP WITHOUT TIME ZONE,
    update_at           TIMESTAMP WITHOUT TIME ZONE,
    is_active           BOOLEAN,
    account_expired     BOOLEAN,
    credentials_expired BOOLEAN,
    account_locked      BOOLEAN,
    id_endereco         BIGINT,
    role                VARCHAR(255),
    CONSTRAINT pk_patient PRIMARY KEY (id)
);

ALTER TABLE patient
    ADD CONSTRAINT uc_patient_email UNIQUE (email);

ALTER TABLE patient
    ADD CONSTRAINT FK_PATIENT_ON_ID_ENDERECO FOREIGN KEY (id_endereco) REFERENCES address (id);

CREATE TABLE appointment
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    appointment_date        date,
    uuid                    UUID,
    appointment_start_time  time WITHOUT TIME ZONE,
    appointment_end_time    time WITHOUT TIME ZONE,
    appointment_description VARCHAR(255),
    appointment_status      VARCHAR(255),
    doctor_id               BIGINT,
    patient_id              BIGINT,
    CONSTRAINT pk_appointment PRIMARY KEY (id)
);

ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_DOCTOR FOREIGN KEY (doctor_id) REFERENCES doctor (id);

ALTER TABLE appointment
    ADD CONSTRAINT FK_APPOINTMENT_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id);


INSERT INTO admin (name, email, password, is_active, uuid, account_expired, credentials_expired, account_locked, role)
VALUES ('Eliseu Silva', 'admin@example.com', '$2a$12$jK9tpMJAxtULd.PnIslDQupQwwqCRxhLAd8kkB2ad4T1FW3Bo1986', true, gen_random_uuid(), false, false, false, 'ADMIN'); --Senha: Senha_forte123

INSERT INTO address (cep, logradouro, complemento, numero, bairro, localidade, uf, ibge, gia, ddd, siafi)
VALUES
    ('12345678', 'Street 1', 'Apt 101', 123, 'Neighborhood 1', 'City 1', 'State 1', '1234567', '1234', '11', '1234'),
    ('54321876', 'Street 2', 'Apt 202', 456, 'Neighborhood 2', 'City 2', 'State 2', '7654321', '5678', '22', '5678'),
    ('98765432', 'Street 3', 'Apt 303', 789, 'Neighborhood 3', 'City 3', 'State 3', '4321098', '9101', '33', '9101'),
    ('13579246', 'Street 4', 'Apt 404', 1011, 'Neighborhood 4', 'City 4', 'State 4', '9876543', '1121', '44', '1121'),
    ('86420159', 'Street 5', 'Apt 505', 1213, 'Neighborhood 5', 'City 5', 'State 5', '2468013', '3141', '55', '3141');

--senha: Abcd_1234
INSERT INTO patient (uuid, nome, email, senha, telefone, cpf, create_at, update_at, is_active, account_expired, credentials_expired, account_locked, id_endereco, role)
VALUES
    (gen_random_uuid(), 'Ana Silva', 'ana.silva@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', '(11)12345-6789', '12345678901', NOW(), NOW(), true, false, false, false, 3, 'PATIENT'),
    (gen_random_uuid(), 'João Pereira', 'joao.pereira@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', '(21)23456-7890', '23456789012', NOW(), NOW(), true, false, false, false, 2, 'PATIENT'),
    (gen_random_uuid(), 'Maria Santos', 'maria.santos@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', '(31)34567-8901', '34567890123', NOW(), NOW(), true, false, false, false, 3, 'PATIENT'),
    (gen_random_uuid(), 'Pedro Almeida', 'pedro.almeida@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', '(41)45678-9012', '45678901234', NOW(), NOW(), true, false, false, false, 4, 'PATIENT'),
    (gen_random_uuid(), 'Marcela Rodrigues', 'marcela.rodrigues@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', '(51)56789-0123', '56789012345', NOW(), NOW(), true, false, false, false, 5, 'PATIENT'),
    (gen_random_uuid(), 'Lucas Oliveira', 'lucas.oliveira@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', '(61)67890-1234', '67890123456', NOW(), NOW(), true, false, false, false, 3, 'PATIENT'),
    (gen_random_uuid(), 'Juliana Lima', 'juliana.lima@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', '(71)78901-2345', '78901234567', NOW(), NOW(), true, false, false, false, 2, 'PATIENT'),
    (gen_random_uuid(), 'Marcos Souza', 'marcos.souza@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', '(81)89012-3456', '89012345678', NOW(), NOW(), true, false, false, false, 3, 'PATIENT'),
    (gen_random_uuid(), 'Camila Martins', 'camila.martins@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', '(91)90123-4567', '90123456789', NOW(), NOW(), true, false, false, false, 4, 'PATIENT'),
    (gen_random_uuid(), 'Rafael Faria', 'rafael.faria@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', '(99)01234-5678', '01234567890', NOW(), NOW(), true, false, false, false, 5, 'PATIENT');

INSERT INTO doctor (name, crm, email, password, is_active, specialty, uuid, account_expired, credentials_expired, account_locked, role, address_id)
VALUES
    ('Gabriela Silva', '12345-SP', 'gabriela.silva@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', true, 'Specialty 1', gen_random_uuid(), false, false, false, 'DOCTOR', 1),
    ('Thiago Santos', '23456-RJ', 'thiago.santos@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', true, 'Specialty 2', gen_random_uuid(), false, false, false, 'DOCTOR', 1),
    ('Larissa Oliveira', '34567-MG', 'larissa.oliveira@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', true, 'Specialty 3', gen_random_uuid(), false, false, false, 'DOCTOR', 1),
    ('Bruno Costa', '45678-BA', 'bruno.costa@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', true, 'Specialty 4', gen_random_uuid(), false, false, false, 'DOCTOR', 1),
    ('Isabela Pereira', '56789-RS', 'isabela.pereira@example.com', '$2a$12$2HAkB9tD0TF2lWacfY.6cOIAYgM29MnpdUBx.cMU66qX51HsqHWs6', true, 'Specialty 5', gen_random_uuid(), false, false, false, 'DOCTOR', 1);

INSERT INTO appointment (appointment_date, uuid, appointment_start_time, appointment_end_time, appointment_description, appointment_status, doctor_id, patient_id)
VALUES
    ('2024-04-27', gen_random_uuid(), '08:00:00', '08:30:00', 'Consulta', 'WAITING', 1, 1),
    ('2024-04-28', gen_random_uuid(), '09:00:00', '09:30:00', 'Consulta', 'WAITING', 2, 2),
    ('2024-04-29', gen_random_uuid(), '10:00:00', '10:30:00', 'Consulta', 'WAITING', 3, 3),
    ('2024-04-30', gen_random_uuid(), '11:00:00', '11:30:00', 'Consulta', 'WAITING', 4, 4),
    ('2024-05-01', gen_random_uuid(), '12:00:00', '12:30:00', 'Consulta', 'WAITING', 5, 5);
